//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace TimelessTreasuresWeb.ServiceReference1
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Item", Namespace = "http://schemas.datacontract.org/2004/07/TempService")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimelessTreasuresWeb.ServiceReference1.CartTracker[] CartTrackersField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSoldField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Visible_Field;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimelessTreasuresWeb.ServiceReference1.CartTracker[] CartTrackers
        {
            get
            {
                return this.CartTrackersField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CartTrackersField, value) != true))
                {
                    this.CartTrackersField = value;
                    this.RaisePropertyChanged("CartTrackers");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CategoryField, value) != true))
                {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true))
                {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((this.IdField.Equals(value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ImageField, value) != true))
                {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSold
        {
            get
            {
                return this.NumSoldField;
            }
            set
            {
                if ((this.NumSoldField.Equals(value) != true))
                {
                    this.NumSoldField = value;
                    this.RaisePropertyChanged("NumSold");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                if ((this.PriceField.Equals(value) != true))
                {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                if ((this.QuantityField.Equals(value) != true))
                {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitleField, value) != true))
                {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Visible_
        {
            get
            {
                return this.Visible_Field;
            }
            set
            {
                if ((this.Visible_Field.Equals(value) != true))
                {
                    this.Visible_Field = value;
                    this.RaisePropertyChanged("Visible_");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CartTracker", Namespace = "http://schemas.datacontract.org/2004/07/TempService")]
    [System.SerializableAttribute()]
    public partial class CartTracker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimelessTreasuresWeb.ServiceReference1.Item ItemField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimelessTreasuresWeb.ServiceReference1.UCart UCartField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartId
        {
            get
            {
                return this.CartIdField;
            }
            set
            {
                if ((this.CartIdField.Equals(value) != true))
                {
                    this.CartIdField = value;
                    this.RaisePropertyChanged("CartId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimelessTreasuresWeb.ServiceReference1.Item Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ItemField, value) != true))
                {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                if ((this.PriceField.Equals(value) != true))
                {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdID
        {
            get
            {
                return this.ProdIDField;
            }
            set
            {
                if ((this.ProdIDField.Equals(value) != true))
                {
                    this.ProdIDField = value;
                    this.RaisePropertyChanged("ProdID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                if ((this.QuantityField.Equals(value) != true))
                {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimelessTreasuresWeb.ServiceReference1.UCart UCart
        {
            get
            {
                return this.UCartField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UCartField, value) != true))
                {
                    this.UCartField = value;
                    this.RaisePropertyChanged("UCart");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UCart", Namespace = "http://schemas.datacontract.org/2004/07/TempService")]
    [System.SerializableAttribute()]
    public partial class UCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimelessTreasuresWeb.ServiceReference1.CartTracker[] CartTrackersField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimelessTreasuresWeb.ServiceReference1.Customer CustomerField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimelessTreasuresWeb.ServiceReference1.CartTracker[] CartTrackers
        {
            get
            {
                return this.CartTrackersField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CartTrackersField, value) != true))
                {
                    this.CartTrackersField = value;
                    this.RaisePropertyChanged("CartTrackers");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustId
        {
            get
            {
                return this.CustIdField;
            }
            set
            {
                if ((this.CustIdField.Equals(value) != true))
                {
                    this.CustIdField = value;
                    this.RaisePropertyChanged("CustId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimelessTreasuresWeb.ServiceReference1.Customer Customer
        {
            get
            {
                return this.CustomerField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerField, value) != true))
                {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((this.IdField.Equals(value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                if ((this.TotalField.Equals(value) != true))
                {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Customer", Namespace = "http://schemas.datacontract.org/2004/07/TempService")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustAddressField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustPhoneNoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimelessTreasuresWeb.ServiceReference1.PUser PUserField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimelessTreasuresWeb.ServiceReference1.UCart[] UCartsField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustAddress
        {
            get
            {
                return this.CustAddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustAddressField, value) != true))
                {
                    this.CustAddressField = value;
                    this.RaisePropertyChanged("CustAddress");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustId
        {
            get
            {
                return this.CustIdField;
            }
            set
            {
                if ((this.CustIdField.Equals(value) != true))
                {
                    this.CustIdField = value;
                    this.RaisePropertyChanged("CustId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustPhoneNo
        {
            get
            {
                return this.CustPhoneNoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustPhoneNoField, value) != true))
                {
                    this.CustPhoneNoField = value;
                    this.RaisePropertyChanged("CustPhoneNo");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                if ((this.DateOfBirthField.Equals(value) != true))
                {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimelessTreasuresWeb.ServiceReference1.PUser PUser
        {
            get
            {
                return this.PUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PUserField, value) != true))
                {
                    this.PUserField = value;
                    this.RaisePropertyChanged("PUser");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimelessTreasuresWeb.ServiceReference1.UCart[] UCarts
        {
            get
            {
                return this.UCartsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UCartsField, value) != true))
                {
                    this.UCartsField = value;
                    this.RaisePropertyChanged("UCarts");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PUser", Namespace = "http://schemas.datacontract.org/2004/07/TempService")]
    [System.SerializableAttribute()]
    public partial class PUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimelessTreasuresWeb.ServiceReference1.Admin AdminField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimelessTreasuresWeb.ServiceReference1.Customer CustomerField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UEmailField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFullNameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPasswordField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USurnameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UcreationtimeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UroleField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimelessTreasuresWeb.ServiceReference1.Admin Admin
        {
            get
            {
                return this.AdminField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AdminField, value) != true))
                {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimelessTreasuresWeb.ServiceReference1.Customer Customer
        {
            get
            {
                return this.CustomerField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerField, value) != true))
                {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UEmail
        {
            get
            {
                return this.UEmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UEmailField, value) != true))
                {
                    this.UEmailField = value;
                    this.RaisePropertyChanged("UEmail");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UFullName
        {
            get
            {
                return this.UFullNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UFullNameField, value) != true))
                {
                    this.UFullNameField = value;
                    this.RaisePropertyChanged("UFullName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UId
        {
            get
            {
                return this.UIdField;
            }
            set
            {
                if ((this.UIdField.Equals(value) != true))
                {
                    this.UIdField = value;
                    this.RaisePropertyChanged("UId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPassword
        {
            get
            {
                return this.UPasswordField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UPasswordField, value) != true))
                {
                    this.UPasswordField = value;
                    this.RaisePropertyChanged("UPassword");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USurname
        {
            get
            {
                return this.USurnameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.USurnameField, value) != true))
                {
                    this.USurnameField = value;
                    this.RaisePropertyChanged("USurname");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ucreationtime
        {
            get
            {
                return this.UcreationtimeField;
            }
            set
            {
                if ((this.UcreationtimeField.Equals(value) != true))
                {
                    this.UcreationtimeField = value;
                    this.RaisePropertyChanged("Ucreationtime");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urole
        {
            get
            {
                return this.UroleField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UroleField, value) != true))
                {
                    this.UroleField = value;
                    this.RaisePropertyChanged("Urole");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UserNameField, value) != true))
                {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Admin", Namespace = "http://schemas.datacontract.org/2004/07/TempService")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdminIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdminPermsField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimelessTreasuresWeb.ServiceReference1.PUser PUserField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdminId
        {
            get
            {
                return this.AdminIdField;
            }
            set
            {
                if ((this.AdminIdField.Equals(value) != true))
                {
                    this.AdminIdField = value;
                    this.RaisePropertyChanged("AdminId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdminPerms
        {
            get
            {
                return this.AdminPermsField;
            }
            set
            {
                if ((this.AdminPermsField.Equals(value) != true))
                {
                    this.AdminPermsField = value;
                    this.RaisePropertyChanged("AdminPerms");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimelessTreasuresWeb.ServiceReference1.PUser PUser
        {
            get
            {
                return this.PUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PUserField, value) != true))
                {
                    this.PUserField = value;
                    this.RaisePropertyChanged("PUser");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ItemWrapper", Namespace = "http://schemas.datacontract.org/2004/07/TempService")]
    [System.SerializableAttribute()]
    public partial class ItemWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSoldField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VisibilityField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CategoryField, value) != true))
                {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true))
                {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ImageField, value) != true))
                {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSold
        {
            get
            {
                return this.NumSoldField;
            }
            set
            {
                if ((this.NumSoldField.Equals(value) != true))
                {
                    this.NumSoldField = value;
                    this.RaisePropertyChanged("NumSold");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                if ((this.PriceField.Equals(value) != true))
                {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                if ((this.QuantityField.Equals(value) != true))
                {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TitleField, value) != true))
                {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Visibility
        {
            get
            {
                return this.VisibilityField;
            }
            set
            {
                if ((this.VisibilityField.Equals(value) != true))
                {
                    this.VisibilityField = value;
                    this.RaisePropertyChanged("Visibility");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference1.IService1")]
    public interface IService1
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/returnList", ReplyAction = "http://tempuri.org/IService1/returnListResponse")]
        TimelessTreasuresWeb.ServiceReference1.Item[] returnList();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/returnList", ReplyAction = "http://tempuri.org/IService1/returnListResponse")]
        System.Threading.Tasks.Task<TimelessTreasuresWeb.ServiceReference1.Item[]> returnListAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/Register", ReplyAction = "http://tempuri.org/IService1/RegisterResponse")]
        string Register(string Email, string Name, string Username, string Surname, string Number, string Password, string Address);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/Register", ReplyAction = "http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string Email, string Name, string Username, string Surname, string Number, string Password, string Address);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/login", ReplyAction = "http://tempuri.org/IService1/loginResponse")]
        string login(string Email, string Password);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/login", ReplyAction = "http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<string> loginAsync(string Email, string Password);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/getProducts", ReplyAction = "http://tempuri.org/IService1/getProductsResponse")]
        void getProducts();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/getProducts", ReplyAction = "http://tempuri.org/IService1/getProductsResponse")]
        System.Threading.Tasks.Task getProductsAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/addItemsToDB", ReplyAction = "http://tempuri.org/IService1/addItemsToDBResponse")]
        string addItemsToDB(string title, decimal price, string desciption, string category, string image);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/addItemsToDB", ReplyAction = "http://tempuri.org/IService1/addItemsToDBResponse")]
        System.Threading.Tasks.Task<string> addItemsToDBAsync(string title, decimal price, string desciption, string category, string image);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/AddDummyData", ReplyAction = "http://tempuri.org/IService1/AddDummyDataResponse")]
        void AddDummyData();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/AddDummyData", ReplyAction = "http://tempuri.org/IService1/AddDummyDataResponse")]
        System.Threading.Tasks.Task AddDummyDataAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/getItems", ReplyAction = "http://tempuri.org/IService1/getItemsResponse")]
        TimelessTreasuresWeb.ServiceReference1.ItemWrapper[] getItems(int SortType);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/getItems", ReplyAction = "http://tempuri.org/IService1/getItemsResponse")]
        System.Threading.Tasks.Task<TimelessTreasuresWeb.ServiceReference1.ItemWrapper[]> getItemsAsync(int SortType);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/filterAndSortItems", ReplyAction = "http://tempuri.org/IService1/filterAndSortItemsResponse")]
        TimelessTreasuresWeb.ServiceReference1.Item[] filterAndSortItems(string filterOrder, string sortOrder);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/filterAndSortItems", ReplyAction = "http://tempuri.org/IService1/filterAndSortItemsResponse")]
        System.Threading.Tasks.Task<TimelessTreasuresWeb.ServiceReference1.Item[]> filterAndSortItemsAsync(string filterOrder, string sortOrder);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/AddItemToCart", ReplyAction = "http://tempuri.org/IService1/AddItemToCartResponse")]
        string AddItemToCart(int Prodid, int UserId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/AddItemToCart", ReplyAction = "http://tempuri.org/IService1/AddItemToCartResponse")]
        System.Threading.Tasks.Task<string> AddItemToCartAsync(int Prodid, int UserId);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TimelessTreasuresWeb.ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TimelessTreasuresWeb.ServiceReference1.IService1>, TimelessTreasuresWeb.ServiceReference1.IService1
    {

        public Service1Client()
        {
        }

        public Service1Client(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public Service1Client(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public TimelessTreasuresWeb.ServiceReference1.Item[] returnList()
        {
            return base.Channel.returnList();
        }

        public System.Threading.Tasks.Task<TimelessTreasuresWeb.ServiceReference1.Item[]> returnListAsync()
        {
            return base.Channel.returnListAsync();
        }

        public string Register(string Email, string Name, string Username, string Surname, string Number, string Password, string Address)
        {
            return base.Channel.Register(Email, Name, Username, Surname, Number, Password, Address);
        }

        public System.Threading.Tasks.Task<string> RegisterAsync(string Email, string Name, string Username, string Surname, string Number, string Password, string Address)
        {
            return base.Channel.RegisterAsync(Email, Name, Username, Surname, Number, Password, Address);
        }

        public string login(string Email, string Password)
        {
            return base.Channel.login(Email, Password);
        }

        public System.Threading.Tasks.Task<string> loginAsync(string Email, string Password)
        {
            return base.Channel.loginAsync(Email, Password);
        }

        public void getProducts()
        {
            base.Channel.getProducts();
        }

        public System.Threading.Tasks.Task getProductsAsync()
        {
            return base.Channel.getProductsAsync();
        }

        public string addItemsToDB(string title, decimal price, string desciption, string category, string image)
        {
            return base.Channel.addItemsToDB(title, price, desciption, category, image);
        }

        public System.Threading.Tasks.Task<string> addItemsToDBAsync(string title, decimal price, string desciption, string category, string image)
        {
            return base.Channel.addItemsToDBAsync(title, price, desciption, category, image);
        }

        public void AddDummyData()
        {
            base.Channel.AddDummyData();
        }

        public System.Threading.Tasks.Task AddDummyDataAsync()
        {
            return base.Channel.AddDummyDataAsync();
        }

        public TimelessTreasuresWeb.ServiceReference1.ItemWrapper[] getItems(int SortType)
        {
            return base.Channel.getItems(SortType);
        }

        public System.Threading.Tasks.Task<TimelessTreasuresWeb.ServiceReference1.ItemWrapper[]> getItemsAsync(int SortType)
        {
            return base.Channel.getItemsAsync(SortType);
        }

        public TimelessTreasuresWeb.ServiceReference1.Item[] filterAndSortItems(string filterOrder, string sortOrder)
        {
            return base.Channel.filterAndSortItems(filterOrder, sortOrder);
        }

        public System.Threading.Tasks.Task<TimelessTreasuresWeb.ServiceReference1.Item[]> filterAndSortItemsAsync(string filterOrder, string sortOrder)
        {
            return base.Channel.filterAndSortItemsAsync(filterOrder, sortOrder);
        }

        public string AddItemToCart(int Prodid, int UserId)
        {
            return base.Channel.AddItemToCart(Prodid, UserId);
        }

        public System.Threading.Tasks.Task<string> AddItemToCartAsync(int Prodid, int UserId)
        {
            return base.Channel.AddItemToCartAsync(Prodid, UserId);
        }
    }
}
